### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by fro-profesional** [skoshx/pentagon#2]
Can you explain a little this?

`
const db = createPentagon(kv, {
  users: {
    schema: User,
    relations: {
      myOrders: ["orders", [Order], undefined, "userId"],
    },
  },
  orders: {
    schema: Order,
    relations: {
      user: ["users", User, "userId", "id"],
    },
  },
});

// Now 
the undefined is not clear to me

**Comment by fro-profesional** [comment]
Can you open discussions?

**Comment by skoshx** [comment]
@fro-profesional Answered you on Discord! :)

**Comment by fro-profesional** [comment]
https://discord.com/channels/684898665143206084/1114722327314309180
