### ISSUE TITLE
[Bug]: Error: Could not update item.

### ISSUE THREAD

**Issue by waptik** [skoshx/pentagon#26]
So i'm trying to update information and i got the error below:

```sh
Error: Could not update item.
    at update (https://deno.land/x/pentagon@v0.1.1/src/crud.ts:110:9)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async updateManyImpl (https://deno.land/x/pentagon@v0.1.1/src/pentagon.ts:156:10)
    at async updateImpl (https://deno.land/x/pentagon@v0.1.1/src/pentagon.ts:169:11)
    at async Database.updateUser (file:///Users/steve/code/my_projects/xxx/utils/db.ts:194:18)
```

Here's a redacted version of the table's zod schema
```ts
export const User = z.object({
  id: z.number().describe("primary, unique"),
  firstName: z.string(),
  lastName: z.string().optional(),
  nickname: z.string().describe("unique"),
  createdAt: z.date(),
  updatedAt: z.date().nullable(),
});
```
And here's how i'm calling the `updateUser` method
```ts
  await db.updateUser(ctx.from!.id, {
        firstName: this.firstName,
        lastName: this.lastName,
      })
```
![image](https://github.com/skoshx/pentagon/assets/1687551/140ff02e-2551-4c36-a7f9-3f92d89db051)

**Comment by OlexG** [comment]
+1
Experiencing the same issue 
Same exact access pattern too

**Comment by waptik** [comment]
> +1 Experiencing the same issue Same exact access pattern too

This really sucks. Right now i have to use the generic way of updating the database but it gets complicated with advanced keys which i have a lot.
I'd either have to replace this library with another stable one or go 100% generic

**Comment by skoshx** [comment]
Hello, thanks for opening this issue! Will look into this bug ASAP! in the meanwhile, if one of you already has a minimal reproduction, that would help out a lot! :)

**Comment by waptik** [comment]
> Hello, thanks for opening this issue! Will look into this bug ASAP! in the meanwhile, if one of you already has a minimal reproduction, that would help out a lot! :)

Sorry, i missed this.

> Just created a reproduction, now looking for a fix

Fantastic! Looking forward to the fix. Whilst you're at it, please also try to validate whether the `delete` method works as i have yet to give it a try.

**Comment by skoshx** [comment]
@waptik Hello, this particular issue is now fixed, but there is still another issue (`findMany` returning duplicates if multiple indexes #27 ), so I will try to fix it as well ASAP and then create a release.

Btw, you can refer to the regression tests created for this issue (there are some things in your example code such as having `primary` AND `unique`) which includes the working example! :)

I can let you know here when I create the release with the fixes 👍

**Comment by waptik** [comment]
Hi @skoshx , thanks for the fix. I really appreciate it. I haven't used anything other than `.create()` , `.find()` and `.update()`.

I'm looking forward to a positive progress and future release based on fixes related to this issue

**Comment by skoshx** [comment]
Hello @waptik , `v0.1.2` is now released, with all the current known bugs fixed! :)

**Comment by waptik** [comment]
> Hello @waptik , `v0.1.2` is now released, with all the current known bugs fixed! :)

I can confirm that the bug i found has been fixed and no issue with `findMany` so far.
Thanks for help
