### ISSUE TITLE
Infer return type when using `include`

### ISSUE THREAD

**Issue by skoshx** [skoshx/pentagon#3]
When we're using `include` when querying for data, the  type of `include` is fully-typed, but the return value doesn't yet infer in a way that takes the `include` into consideration.

All help is appreciated!

**Comment by lilnasy** [comment]
Addressed by #6.

**Comment by jnssnmrcs** [comment]
Just wanted to let you know I'm working on types for find functions, I've managed to get them to work exactly like it does in prisma (nesting select/include etc infinite), but it's not ready for PR yet.
