### ISSUE TITLE
[Bug]: `.create` doesn't return extended and merged values

### ISSUE THREAD

**Issue by waptik** [skoshx/pentagon#33]
As you can see from the screenshot, the fields in `WithDefautTimestamps` and `WithDefaultId` are not being returned immediately are using the `.create` method

I have updated my [demo repo](https://github.com/waptik/test-deno-pentagon) with a [new branch
](https://github.com/waptik/test-deno-pentagon/tree/feat/WithDefaultId) to reflect these changes

![image](https://github.com/skoshx/pentagon/assets/1687551/e0667a72-ec59-4eeb-9ee1-24a0ffabab59)

**Comment by waptik** [comment]
# Update:

Looks like it had nothing to do with using zod's `.extend` or `.merge` but because i defined default values for them. If you manually set these values when creating a new entry, they get returned back upon creation

Here's the code and terminal output of a case in another project

<details>
<summary>Code</summary>

![image](https://github.com/skoshx/pentagon/assets/1687551/97332ce3-5384-408f-8fc8-0ae09a3f4c8b)

</details>

<details>
<summary>terminal output</summary>

![image](https://github.com/skoshx/pentagon/assets/1687551/184ee51e-6cf5-4a91-9cb7-d37a05b9c845)
VS
![image](https://github.com/skoshx/pentagon/assets/1687551/1f077619-997e-4251-924d-9409d0a168d2)


</details>

**Comment by skoshx** [comment]
thanks for opening this issue! Just to clarify, the if the values have a default value, the  default values don't get returned when calling `.create`?

**Comment by waptik** [comment]
> thanks for opening this issue! Just to clarify, the if the values have a default value, the default values don't get returned when calling `.create`?

Yes, if the fields have a default set, they don't get returned. You have to manually set them when creating a new entry

**Comment by skoshx** [comment]
Hello, this is fixed in the newest commit! Thanks for opening this issue :)

**Comment by waptik** [comment]
> Hello, this is fixed in the newest commit! Thanks for opening this issue :)

Hey, thanks. I can confirm that this issue has been fixed in `v0.1.4`
