### ISSUE TITLE
Enforce `unique` for keys

### ISSUE THREAD

**Issue by skoshx** [skoshx/pentagon#4]

**Comment by lilnasy** [comment]
What do you mean by this?

**Comment by skoshx** [comment]
@lilnasy This is basically when we mark keys as unique with the `.describe("unique")`, so if we have a schema like

```typescript
{
  id: z.string().uuid().describe("primary, unique"),
  email: z.string().describe("unique")
}
```

We need to enforce that we're not allowed to create any items with existing values or update any items that break the `unique` constraints

**Comment by jnssnmrcs** [comment]
what's your definition of `index` and `unique` here? because it seems like properties with `index` attribute are treated as unique indexes in the code at the moment.

**Comment by skoshx** [comment]
@jnssnmrcs `index` is meant to be used to do secondary indexing so for instance index by email key, but now that you mention it, yeah, `index` is treated basically as unique indexes, which is wrong I think?

You bring up a good point in the implementation of the secondary key indexing, not sure how it should be implemented so that an indexed key doesn't have to be unique, without adding too much extra complexity to the implementation...

**Comment by jnssnmrcs** [comment]
Yea I was just reading up about the differences and came across this answer on stackoverflow which explained how it works in MySQL: https://stackoverflow.com/a/708508/8952488

It also feels superfluous to say that a primary is also unique (like you do in most examples), since a primary index is always unique.
