### ISSUE TITLE
Error when trying to include empty relation.

### ISSUE THREAD

**Issue by sntran** [skoshx/pentagon#8]
When the `users` has a `myOrders` relation, but there is no `Order` in the database yet, a `findFirst` with `include` for `myOrder` would throws error.

Expected Result: return me the user with empty `myOrders`.

Playground: https://dash.deno.com/playground/happy-goat-63

**Comment by skoshx** [comment]
Thanks a lot for opening an issue, will fix this and release a new version tomorrow! :)

**Comment by skoshx** [comment]
Hello, sorry for the delay, but this is now fixed in commit [7ffdcf5](https://github.com/skoshx/pentagon/commit/7ffdcf5f7cead8e2bba273b5274a42fe2fcbb097)! :) Will push a `minor` update in a few.

**Comment by sntran** [comment]
Thanks! That commit does not look like a "minor" one at all :D

**Comment by skoshx** [comment]
Haha, not following SemVer is my guilty pleasure :D
